### ISSUE TITLE
`:Format` adds a text `null` to an empty file with multiple formatters

### ISSUE THREAD

**Issue by seong-hun** [mhartington/formatter.nvim#147]
First of all, I really appreciate your usefull plugin that makes formatting very easy.
Also, please note that I'm very new to neovim, although I've experienced vim for several years.

I have the following lua rc file.

```lua
local formatter = require('formatter')

formatter.setup {
	-- All formatter configurations are opt-in
	filetype = {
		python = {
			-- Pick from defaults:
			require('formatter.filetypes.python').black,
			require('formatter.filetypes.python').isort,
		}
	}
}
```

When I run `:Format` in an empty file, for example `__init__.py`,
a work `null` is automatically added to the file.

If I use a single formatter in the rc file, for example

```lua
local formatter = require('formatter')

formatter.setup {
	-- All formatter configurations are opt-in
	filetype = {
		python = {
			-- Pick from defaults:
			require('formatter.filetypes.python').black
                        -- or require('formatter.filetypes.python').isort
		}
	}
}
```

it does not happen, which may imply that it is not the problem of the formatters itself.

**Comment by Hrle97** [comment]
@seong-hun please check out #148 - it should fix this

**Comment by KPatr1ck** [comment]
It seem still exists.
When formatting my empty python file, it does add "v: null" to the file.

My config:
```lua
formatter.setup({
    filetype = {
        lua = {
            function()
                return {
                    exe = 'stylua',
                    args = {
                        -- "--config-path "
                        --   .. os.getenv("XDG_CONFIG_HOME")
                        --   .. "/stylua/stylua.toml",
                        '-',
                    },
                    stdin = true,
                }
            end,
        },
        python = {
            function()
                return {
                    exe = 'yapf',
                    stdin = true,
                }
            end,
            function()
                return {
                    exe = 'autopep8',
                    args = { '-' },
                    stdin = true,
                }
            end,
            function()
                return {
                    exe = 'isort',
                    args = { '-q', '-' },
                    stdin = true,
                }
            end,
            -- function()
            --     return {
            --         exe = 'docformatter',
            --         args = { '-' },
            --         stdin = true,
            --     }
            -- end,
            function()
                return {
                    exe = 'black',
                    args = {
                        '-q',
                        '-',
                    },
                    stdin = true,
                }
            end,
            -- function()
            --     return {
            --         exe = 'pyment',
            --         args = { '-w', '-' },
            --         stdin = true,
            --     }
            -- end,
            -- function()
            --     return {
            --         exe = 'pydevf',
            --     }
            -- end,
        },
    },
})

```

**Comment by Hrle97** [comment]
heya sry for the wait

ill take a look at this today after work
